name: Update JSONs
on:
  push:
    paths:
      - 'excel/*.xlsx'    # Se activa cuando se modifican archivos Excel
  schedule:
    - cron: '* * * * *'   # Se ejecuta cada minuto    
  workflow_dispatch:      # Esto habilita la ejecución manual  

jobs:
  convert-excel-to-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          pip install pandas openpyxl requests   # Agregado requests aquí
          
      - name: Convert Excel to JSON
        run: python scripts/excel_to_json.py
        
      - name: Commit JSON files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add json/*.json
          # Solo intenta hacer commit si hay cambios
          git diff --staged --quiet || (git commit -m "Update JSONs from Excel" && git push)
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          branch: ${{ github.ref }}